version: '3.6'

services:
    ubuntu1804:
        image: 'ccy1219/docker-img-base:SSH-ubuntu-18.04'
        tty: true
        stdin_open: true
        hostname: 'ubuntu1804'
        ports:
            - "36022:22"
            - "36080:80"
            - "36443:443"

    debian106:
        image: 'ccy1219/docker-img-base:SSH-debian-10.6'
        tty: true
        stdin_open: true
        hostname: 'debian106'
        ports:
            - "36023:22"
            - "36081:80"
            - "36444:443"
