FROM ccy1219/docker-img-base:ubuntu-1804-u

LABEL maintainer="ccy1219@gmail.com"

RUN apt-get update

RUN apt-get install -y nano
RUN apt-get install -y iputils-ping
RUN apt-get install -y iproute2
RUN apt-get install -y htop
RUN apt-get install -y openssh-client
RUN apt-get install -y nfs-common
RUN apt-get install -y acl
